# -*- coding: utf-8 -*-
"""PDFQuery_LangChain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yYK_Y8lzL4z5OKMfdZ8N_1hydi7cfiHT
"""

!pip install -q cassio datasets sentence-transformers langchain-google-genai PyPDF2

from langchain_community.vectorstores import Cassandra
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.text_splitter import RecursiveCharacterTextSplitter
from PyPDF2 import PdfReader
import cassio, os

from PyPDF2 import PdfReader

GEMINI_API_KEY = "AIzaSyD4ZGTpUwDgtuSy5gOudmAulU5d6EPl81s"
os.environ["GOOGLE_API_KEY"] = GEMINI_API_KEY

ASTRA_DB_APPLICATION_TOKEN = "AstraCS:dhkDEeBUpzjgHnNKUqZNuGeZ:713e596503076e7e799e937491708e01e632b7153124aad9998784a978290a9a"
ASTRA_DB_ID = "90877930-b5df-4767-934e-79a3321e4d04"

pdfreader = PdfReader('budget_speech_english_0.pdf')

from typing_extensions import Concatenate
raw_text = ''
for i, page in enumerate(pdfreader.pages):
      content = page.extract_text()
      if content:
        raw_text+=content

raw_text

from langchain.text_splitter import RecursiveCharacterTextSplitter

def split_text(text, chunk_size=1000, chunk_overlap=150):
    """Split raw text into overlapping chunks for embeddings."""
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=["\n\n", "\n", ".", "!", "?", ",", " ", ""],
    )
    chunks = splitter.split_text(text)
    print(f"✅ Created {len(chunks)} chunks.")
    return chunks

chunks = split_text(raw_text)

cassio.init(token=ASTRA_DB_APPLICATION_TOKEN,database_id = ASTRA_DB_ID)

"""Create the LangChain Embedding and LLM Objects for later usage"""

embedding = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

"""Create your LangChain Vector Store, backed by Astra DB"""

astra_vector_store = Cassandra(
    embedding = embedding,
    table_name = "qa_mini_demo",
    session = None,
    keyspace = None,
)
astra_vector_store.add_texts(chunks)

chunks[:50]

retriever = astra_vector_store.as_retriever(search_kwargs={"k": 3})

query = "What does the document say about climate change?"

results = astra_vector_store.similarity_search(query, k=3)

for i, doc in enumerate(results, 1):
    print(f"{i}.", doc.page_content[:200], "...\n")